### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by astronouth7303** [astronouth7303/xontrib-z#3]
Might be unique to my laptop, but
```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\site-packages\xonsh\events.py", line 136, in fire
    rv = handler(*pargs, **kwargs)
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\site-packages\xontrib\z.py", line 211, in cd_handler
    self.add(self.getpwd())
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\site-packages\xontrib\z.py", line 192, in add
    self.save_data(data)
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\site-packages\xontrib\z.py", line 119, in save_data
    shutil.copy(f.name, self.Z_DATA)
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 235, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\James\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\James\\AppData\\Local\\Temp\\tmp6uhp2152'
Exception raised in event handler; ignored.
```

**Comment by astronouth7303** [comment]
Note that I don't currently have a windows system, and I personally don't use it on my own equipment.
